In [3]:
import numpy as np
MatrikSaya = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [4]:
print(MatrikSaya)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [5]:
print(type(MatrikSaya))

<class 'numpy.ndarray'>


In [6]:
MatrikSaya.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])